#' Completion of all gaps in the data matrix
#'
#' Gap filling is processed in two steps:
#'
#'  1. Extrapolation and interpolation with time-series models,
#'  2. Imputation of country-specific medians
#'
#' Both attempts dont consider the original reported values (variable obs_value) for processing, but the ratios of obs_values
#' to the respective values from national accounts. For the extrapolation step these ratios are projected backwards and forwards
#' (and in-between available observations) and the estimated observation value is then generated by applying these ratios to
#' the respective value from national accounts. For the second attempt, which is only applied if no single observation is
#' available for the hierarchy level under consideration, relative values of EGSS to national accounts data are calculated for
#' all countries who delivered data for the relevant variable (production, employees, value added or exports). From these
#' ratios a median ratio is applied to the national account data of the country to impute.
#' ATTENTION: The number of countries contributing to this median could differ from year to year!
#'
#' @param x EGSS-data set enriched with national account data (output of function loadNA)
#' @return y Completed EGSS-data set (gaps filled with extrapolation and country-specific medians)
#'
#' @examples
#' data("dat_egssBas")
#' data("natAcc")
#' datEgss <- loadEGSS(x = dat_egssBas)
#' datEgssNA <- loadNA(x = natAcc, y = datEgss, toEst = 2016, t1 = "TOT_EGSS")
#' datEgssNA <- datEgssNA[!(geo %in% c("TR","CH")),]
#' datEgssNA <- datEgssNA[!(indic_pi == "EXP"),]
#' datComp <- gapFill(x = datEgssNA)
#'
#' @import data.table
#' @importFrom stats median
#' @export
#'

gapFill <- function(x){
  orig <- nace_r2 <- ceparema <- obs_value <- yyyy <- code <- obs_valueEX <- rev_val <- obs_gen <- naINDIC <- NULL
  obsMean <- obs_value_relINDIC <- indic_pi <- geo <- ty <- obs_value_rel <- obs_status <- obs_conf <- NULL
  obs_value_relINDIC <- . <- obs_comment <- NULL
  compRate <- nrow(x[orig==TRUE,])/nrow(x)
  cat("The data set contains ",nrow(x)," Observations. ",compRate," of which have been reported. \n")

  # Extrapolation Base Hierarchy .................................................................
  xBas <- x[nace_r2 %in% LETTERS[1:21] &
              ceparema %in% c("CEPA1", "CEPA2", "CEPA3", "CEPA4", "CEPA5", "CEPA6", "CEPA7-9",
                              "CREMA10", "CREMA11", "CREMA13", "CREMA14", "CREMA12_15_16"),]
  nobs0 <- nrow(xBas[is.na(obs_value),])
  cat(nobs0," Observations are missing in the Base Level Hierarchy","\n")

  xBas <- extraPol(xBas)
  setkey(xBas, yyyy, code)
  setkey(x, yyyy, code)
  xBas <- merge(xBas, x, all.x = TRUE)
  xBas[,":=" (obs_value = ifelse(orig == FALSE & !is.na(obs_valueEX), obs_valueEX * rev_val, obs_value),
              obs_gen = ifelse(orig == FALSE & !is.na(obs_valueEX), "EXTRA", obs_gen))]

  xBas[,":=" (obs_value_relINDIC = obs_value/naINDIC)]
  xBas[, obsMean := median(obs_value_relINDIC, na.rm = TRUE), by = .(yyyy, indic_pi, nace_r2, ceparema)]
  xBas[,":=" (obs_value = ifelse(is.na(obs_value), naINDIC * obsMean, obs_value),
              obs_gen = ifelse(is.na(obs_value) & !is.na(naINDIC), "STATE", obs_gen))]
  nobs0 <- nrow(xBas[is.na(obs_value),])
  cat(nobs0," Observations still missing after gap-filling","\n")

  # Extrapolation Ceparema Totals .................................................................
  xCep <- x[nace_r2 == "TOTAL",]
  nobs0 <- nrow(xCep[is.na(obs_value),])
  cat(nobs0," Observations are missing in the Nace TOTAL x Ceparema Hierarchy","\n")

  xCep <- extraPol(xCep)
  setkey(xCep,yyyy,code)
  setkey(x,yyyy,code)
  xCep <- merge(xCep,x,all.x=TRUE)
  xCep[,":=" (obs_value = ifelse(orig == FALSE & !is.na(obs_valueEX), obs_valueEX * rev_val, obs_value),
              obs_gen = ifelse(orig == FALSE & !is.na(obs_valueEX), "EXTRA", obs_gen))]

  xCep[,":=" (obs_value_relINDIC = obs_value/naINDIC)]
  xCep[, obsMean := median(obs_value_relINDIC, na.rm = TRUE), by = .(yyyy, indic_pi, nace_r2, ceparema)]
  xCep[,":=" (obs_value = ifelse(is.na(obs_value), naINDIC * obsMean, obs_value),
              obs_gen = ifelse(is.na(obs_value) & !is.na(naINDIC), "STATE", obs_gen))]
  nobs0 <- nrow(xCep[is.na(obs_value),])
  cat(nobs0," Observations still missing after gap-filling","\n")

  # Extrapolation NACE Totals .................................................................
  # Nace=TOTAL has to be omitted because this Aggregat is already in the xCep data base
  xNac <- x[ceparema %in% c("TOTAL", "TOT_CEPA", "TOT_CREMA") & nace_r2 %in% LETTERS[1:21] ,]
  nobs0 <- nrow(xNac[is.na(obs_value),])
  cat(nobs0," Observations are missing in the Nace x Ceparema TOTAL","\n")

  xNac <- extraPol(xNac)
  setkey(xNac, yyyy, code)
  setkey(x, yyyy, code)
  xNac <- merge(xNac, x, all.x = TRUE)
  xNac[,":=" (obs_value = ifelse(orig == FALSE & !is.na(obs_valueEX), obs_valueEX * rev_val, obs_value),
              obs_gen = ifelse(orig == FALSE & !is.na(obs_valueEX), "EXTRA", obs_gen))]

  xNac[,":=" (obs_value_relINDIC = obs_value/naINDIC)]
  xNac[, obsMean := median(obs_value_relINDIC, na.rm = TRUE), by = .(yyyy, indic_pi, nace_r2, ceparema)]
  xNac[,":=" (obs_value = ifelse(is.na(obs_value), naINDIC * obsMean, obs_value),
              obs_gen = ifelse(is.na(obs_value) & !is.na(naINDIC), "STATE", obs_gen))]
  nobs0 <- nrow(xNac[is.na(obs_value),])
  cat(nobs0," Observations still missing after gap-filling","\n")
  #######################################################################################################
  y <- rbind(xBas, xCep, xNac)
  y <- y[,.(code, geo, yyyy, indic_pi, nace_r2, ceparema, ty, unit, obs_value, rev_val, obs_value_rel, obs_status,
            obs_conf, obs_comment, obs_gen, orig, naINDIC)]
  return(y[])
}

